project:
  type: website
  output-dir: _site

website:
  title: "Marty Marquis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About
  page-footer:
    left: "Built with Quarto"
    right: "Viva La Cascadia"
  repo-url: https://github.com/martymarquis/gh-workshop
  repo-actions: [edit, issue]

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    link-external-newwindow: true
